### ISSUE TITLE
refactor: Move to Rust

### ISSUE THREAD

**Issue by afifurrohman-id** [afifurrohman-id/tempsy-gateway#4]

**Comment by harshRn** [comment]
Hi @afifurrohman-id 
Just wanted to confirm if this is done and dusted by you. Here to contribute in anyway you might need. Thanks!

**Comment by afifurrohman-id** [comment]
> Hi @afifurrohman-id Just wanted to confirm if this is done and dusted by you. Here to contribute in anyway you might need. Thanks!

Hello, sure if you want to contribute it. 
Here i have a few plan still didn't done with me that you may interest in https://github.com/afifurrohman-id/tempsy/issues

**Comment by harshRn** [comment]
Cool! I will see what I could contribute to, and lyk before creating draft PRs. Cheers!
